config/routes.rb
Rails.application.routes.draw do
  resources :advertises
  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
   

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/advertise.rb
class Advertise < ActiveRecord::Base

has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

end

app/models/search.rb
class Search < RailsSimpleSearch::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/advertises_controller.rb
class AdvertisesController < InheritedResources::Base

  private
      
    def advertise_params
      params.require(:advertise).permit(:body,:avatar,:rooms,:city)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/advertises_helper.rb
module AdvertisesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/advertises/_form.html.erb
<%= form_for(@advertise) do |f| %>
  <% if @advertise.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@advertise.errors.count, "error") %> prohibited this advertise from being saved:</h2>
        
      <ul>
      <% @advertise.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <%= f.file_field :avatar %>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
 
 <div class="field">
    <%= f.label :rooms %><br>
<%= select_tag(:rooms, options_for_select([['1', 1], ['2', 2], ['3', 3], ['4', 4] , ['5', 5], ['6', 6]], 2)) %>


  </div>

<div class="field">
    <%= f.label :city %><br>
<%= select_tag(:rooms, options_for_select([['alex', 1], ['cairo', 2], ['aswan', 3], ['menofaya', 4] , ['asyot', 5], ['loxor', 6]], 2)) %>
</div>



  <div class="actions">
    <%= f.submit %>
  </div>


<% end %>

app/views/advertises/edit.html.erb
<h1>Editing Advertise</h1>

<%= render 'form' %>

<%= link_to 'Show', @advertise %> |
<%= link_to 'Back', advertises_path %>

app/views/advertises/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Advertises</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @advertises.each do |advertise| %>
      <tr>
        <td><%= advertise.body %></td>
          
<td><%= image_tag advertise.avatar.url(:thumb) %></td>

        <td><%= link_to 'Show', advertise %></td>
        <td><%= link_to 'Edit', edit_advertise_path(advertise) %></td>

        <td><%= link_to 'Destroy', advertise, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Advertise', new_advertise_path %>

app/views/advertises/new.html.erb
<h1>New Advertise</h1>

<%= render 'form' %>

<%= link_to 'Back', advertises_path %>

app/views/advertises/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @advertise.body %>
</p>

<div style='width: 800px;'>
  <div id="map" style='width: 800px; height: 400px;'></div>
</div>


<%= link_to 'Edit', edit_advertise_path(@advertise) %> |
<%= link_to 'Back', advertises_path %>

<script>

handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers([
    {
      "lat": 0,
      "lng": 0,
      "picture": {
        "url": "https://addons.cdn.mozilla.net/img/uploads/addon_icons/13/13028-64.png",
        "width":  36,
        "height": 36
      },
      "infowindow": "hello!"
    }
  ]);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Arabmap</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
</head>
<body>

<%= yield %>

</body>
</html>